equip/framework

docs/index.md
`equip/equip` should be `equip/framework`.
Once this is merged, a [new build](https://readthedocs.org/projects/equipframework/) should be run manually to fix the links assuming that automated integration has not already been configured.
/cc @shadowhand
=> Fix bad repo links in README

composer.json, src/Responder/FormattedResponder.php, tests/Responder/FormattedResponderTest.php
The formatted responder should keep the formatters in order of
preference, not just in order of addition. By switching to a sorted
dictionary the order will always be correct.
=> Ensure ordering of formatters

src/Handler/JsonContentHandler.php
Original regex did not match valid json content type header:
"application/json; charset=UTF-8"
=> Improve JsonContentHandler regex matching

CHANGELOG.md, src/Handler/ExceptionHandler.php
Whoops's handleException method was halting execution, which meant
that the logging method was never reached.
=> Move exception logging further up in execution

README.md, docs/auth.md, docs/commands.md, docs/session.md
ReadTheDocs has changed from .org to .io for hosted documentation.
=> Update ReadTheDocs links

composer.json, src/Action.php, src/Handler/ActionHandler.php, tests/Handler/ActionHandlerTest.php
Equip uses from there only three getters for Action. Then..
Implement getters.
Add comments.
Add class name as scaler from `::class` keyword.
The `::class` pseudo-constant is resolved at compile-time, and not at runtime. It's a keyword, so does not necessarily depend on the existence of the referenced class.
We can also define properties as private, and to declare this class as final.
@shadowhand what do you think about this?
=> [WIP] Remove unnecessary Arbiter dependency

docs/auth.md
The method name in [ParserInterface](https://github.com/equip/auth/blob/master/src/Jwt/ParserInterface.php#L15) is ```parseToken()``` not ```parse()```.
=> Fixed bad method name in auth docs

docs/auth.md
According to the method signature [Equip\\Auth\\Jwt\\Configuration](https://github.com/equip/auth/blob/master/src/Jwt/Configuration.php) requires 3 parameters:
publicKey
ttl
algorithm
=> Fixed Equip\\Auth\\Jwt\\Configuration parameter definition in auth docs

docs/auth.md
Adapter::validateCredentials() returns an \Equip\Auth\Token instance not a string.
=> [docs] Fixed auth adapter example code

src/Payload.php, tests/PayloadTest.php
Implemented with minimal logic. Your opinion?
I noticed that [some getters of Payload interface](https://github.com/equip/adr/blob/8a618e4e4c9b4f6bc43111deec34817a4f324c0e/src/PayloadInterface.php#L55) should return an `array`, but current implementation may return `null` (and the [current tests](https://github.com/equip/framework/blob/e618b83ff90ffcac0fd6b28a915d7119e40efbbb/tests/PayloadTest.php#L54) use `assertNull`), so I would like to clarify.
```php
$payload = new Payload;
var_dump($payload->getOutput()); // null
$payload = $payload->withOutput([]);
var_dump($payload->getOutput()); // array
```
With this need to do something? 
For example, to initialize the variables as empty array or use a typecast in the methods.
=> [adr 2.0] Implementation of setting methods

src/Resolver/AurynResolver.php, src/Resolver/ResolverTrait.php
This change will allow the use of prepared objects of middleware.
Now [`ResolverTrait::resolve`](https://github.com/equip/framework/blob/b253bd5bf0b4fed4f1c8fe09288904bb16a6b34b/src/Resolver/ResolverTrait.php#L19) method does not check for object and fully trust a conctrete implementation of [`ResolverInterface`](https://github.com/relayphp/Relay.Relay/blob/8268d51e58caa6b95dc8ee9680a2658f6bc288d1/src/ResolverInterface.php). (I hope it will not affect performance) So now any Resolver must return the object back when an instance already exists.
I guess for this case we need to have a test.
=> Allow to use an instance (object) of middleware

src/Formatter/PlatesFormatter.php, tests/Formatter/PlatesFormatterTest.php
The tests will fall because [adr 2.0.0-alpha2](https://github.com/equip/adr/releases/tag/2.0.0-alpha2) is not available (yet) on [Packagist](https://packagist.org/packages/equip/adr).
**UPD.** The test was updated. Now everything should be fine.
=> [adr 2.0] Use Payload::getSetting for PlatesFormatter

CHANGELOG.md, src/Responder/RedirectResponder.php, tests/Responder/RedirectResponderTest.php
The redirect location is not meant to be output as part of the response
body, so it makes more sense to use payload settings.
Refs equip/adr#7
Refs #39
=> Use payload settings for redirect responder

src/Handler/ContentHandler.php, src/Handler/FormContentHandler.php, src/Handler/JsonContentHandler.php, tests/ExceptionTest.php
While the actual content handling comes straight from Relay, we have
some different requirements, specifically in JSON content handling.
Rather than trying to remove these, which could make upgrades more
difficult, remove the parts that are duplication and un-deprecate the
classes that are compatible. This gives us more flexibility to adjust
to Relay upgrades.
Also add in a missing HTTP exception test.
=> Remove deprecation notes on content handlers

src/Exception/FormatterException.php, src/Exception/ResponderException.php
Structure does not allow storage of objects :confused: [`Dictionary::hasValue`](https://github.com/equip/structure/blob/9bb7222d957061b83f4b7b2ae2f85920f8c3c466/src/Dictionary.php#L22)
> array_key_exists(): argument should be either a string or an integer
@shadowhand Please think about the use of [`spl_object_hash`](http://php.net/manual/en/function.spl-object-hash.php) for storing objects.
=> Fix for exceptions

MIGRATING.md, src/Application.php, src/Dispatching/DispatchingSet.php, src/Exception/DispatchingException.php, tests/ApplicationTest.php, tests/Dispatching/DispatchingSetTest.php
Rather than having a single large routing table, split routing into
separate dispatching classes, similar to a middleware set.
See [MIGRATING.md](https://github.com/equip/framework/blob/feature/dispatch-routing/MIGRATING.md) for how it would look to users.
=> Switch from routing to split dispatching

src/Exception/ConfigurationException.php
A configuration may be an existing object. [`Set::hasValue`](https://github.com/equip/structure/blob/9bb7222d957061b83f4b7b2ae2f85920f8c3c466/src/Set.php#L13) (`in_array`)
**TL;DR:**
```php
class ConfigWithoutInterfaceType
{
}
Equip\Application::build()
->setConfiguration([
new ConfigWithoutInterfaceType,
// ...
```
> Catchable fatal error: Object of class Index could not be converted to string
Another case: #62. Really need to update tests for these cases.
=> Fix ConfigurationException

.travis.yml, composer.json, tests/ActionTest.php, tests/ApplicationTest.php, tests/Configuration/ConfigurationSetTest.php, tests/Configuration/EnvConfigurationTest.php, tests/Configuration/RedisConfigurationTest.php, tests/DirectoryTest.php, tests/DirectoryTestCase.php, tests/Dispatching/DispatchingSetTest.php, tests/Formatter/PlatesFormatterTest.php, tests/Handler/DispatchHandlerTest.php, tests/Handler/ExceptionHandlerTest.php, tests/Handler/JsonContentHandlerTest.php, tests/InputTest.php, tests/Middleware/MiddlewareSetTest.php, tests/Responder/FormattedResponderTest.php
PHPUnit >= 5.2 requires PHP 5.6, but the Equip still supports PHP 5.5 (Travis CI)
[PHP 5.5 is no longer supported](https://secure.php.net/supported-versions.php), so it should be removed from the builds.
Now, every build has the warning that the `TestCase::getMock` method has been deprecated.
Ref: [equip/auth/pull/3](https://github.com/equip/auth/pull/3#issuecomment-223382877)
=> Upgrade PHPUnit version to 5.4

src/Directory.php, src/Handler/DispatchHandler.php, tests/DirectoryTest.php, tests/Handler/DispatchHandlerTest.php
When installing Equip inside of a sub-directory it is undesirable to
manually add the directory name to every route. Add prefix support to
Directory collector to handle this.
=> Enable dispatching inside of sub-directory

src/Formatter/FormatterInterface.php, src/Formatter/JsonFormatter.php, src/Formatter/PlatesFormatter.php, tests/Formatter/HtmlFormatterTest.php, tests/Formatter/JsonFormatterTest.php, tests/Formatter/PlatesFormatterTest.php
Coupling formatting to payloads has made formatting arbitrary content
much harder and does not provide a clear separation of concerns.
Allowing formatters to format content from any context provides greater
potential for reuse and will work better with custom responders that
may not use payloads at all.
Refs #76
=> Remove payload from formatting

docs/index.md
I know we already have a link to the sample project in the github README for `equip/framework` but I thought it would be helpful to also include it in the `equipframework.readthedocs.io` docs as well.
=> Add link to create project via the Equip sample project to docs

docs/index.md, src/Contract/ActionInterface.php
Although ActionHandler deals exclusively with ServerRequestInterface
instead of RequestInterface, ActionInterface used just
RequestInterface. This made it impossible for actions to use the
helpful features that ServerRequestInterface offers.
In particular, this bug actually rendered the example Action code in
the docs incorrect, because the variable $request (of type
RequestInterface) was passed as a parameter to input(), which expected
ServerRequestInterface.
=> Make ActionInterface use ServerRequestInterface

src/Configuration/WhoopsConfiguration.php, src/Handler/ExceptionHandler.php, src/Handler/ExceptionHandlerPreferences.php, tests/Handler/ExceptionHandlerPreferencesTest.php, tests/Handler/ExceptionHandlerTest.php
Remove debug stack traces unless the DEBUG_STACKTRACE=1 environment variable is configured.
=> Fix to remove debug stack traces in production environments
